### PR TITLE
Disable the image inferrer in the "tei-on" pipeline

### PR DESCRIPTION
**Pull request by alexwlchan**
Something weird is happening here (see comment in the Terraform) that I don't care to debug properly right now.

### CODE REVIEW

**Review by jamesgorrie — APPROVED** [review]
Good catch a quick-fix, but we should definitely fix this as I am assuming this means images are coming through on the `tei-on` pipeline?

**Comment by alexwlchan** [comment]
> I am assuming this means images are coming through on the tei-on pipeline

Yes.

AIUI, the "tei-on" and "tei-off" pipelines both get the same updates from the source records, but they split post-merger. Image updates will be coming through the "tei-on" pipeline, they're just being ignored. So you won't be able to search for images in "tei-on" – @alicefuzier will know if the TEI work is going to affect images and if that's an issue we strongly care about.

This is mostly about codifying the fix I made manually to unbreak the pipeline, but if people can work out how to fix it properly I'm all ears.

**Comment by jamesgorrie** [comment]
> @alicefuzier will know if the TEI work is going to affect images and if that's an issue we strongly care about.

We have spoken about this previously, and it was definitely something we'd want to be testing, so maybe we'll have to prioritise a fix to make sure we can continue TEI work.

> This is mostly about codifying the fix I made manually to unbreak the pipeline

This is more important so we should definitely get this in soonish

**Comment by alexwlchan** [comment]
Okay, I've merged this for now, and created an issue to track it: https://github.com/wellcomecollection/platform/issues/5292

**Pull request merged**
