### PR TITLE
Create new pipeline 2023 09 01

### PR DESCRIPTION
**Pull request by agnesgaroux**

### CODE REVIEW

**Review by jamieparkinson — COMMENTED** [review]
What are the code changes about?

**Comment by agnesgaroux** [comment]
@jamieparkinson I merged main into `create-new-pipeline-2023-09-01`, not 100% why github doesn't realise that all of these changes are already on `main` 😕

**Comment by agnesgaroux** [comment]
Git tangle ugh..

**Comment by jamieparkinson** [comment]
It looks like the changes were in [this](https://github.com/wellcomecollection/catalogue-pipeline/pull/2433/commits/fce4e57c41f09e3cb908d93c43c64be8e5637ab7) commit - might just be easiest to bin this branch and start again!

**Comment by agnesgaroux** [comment]
Cleaned up > https://github.com/wellcomecollection/catalogue-pipeline/pull/2435

**Pull request closed without merging**
